# Generated by Django 3.2.9 on 2021-11-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name_plural': 'Base Users'},
        ),
    ]
