# Generated by Django 3.2.9 on 2021-11-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
