# Generated by Django 3.2.9 on 2021-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='question_tags', to='main.Tag'),
        ),
    ]
