# Generated by Django 3.2.9 on 2021-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211127_2213'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('type', 'user', 'question', 'answer'), name='vote_constraints'),
        ),
    ]
