# Generated by Django 3.2.9 on 2021-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_vote_vote_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='vote_constraints',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('type', 'user', 'question'), name='question_vote_constraints'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('type', 'user', 'answer'), name='answer_vote_constraints'),
        ),
    ]
